### ISSUE TITLE
[Nostalgia Shader] Settings to modify dimension tint

### ISSUE THREAD

**Issue by jacksonhardaway** [rre36/ShaderpackIssueTracker#9]
**Is your feature request related to a problem? Please describe.**
A setting to disable OR customize the colored tint in the nether and end. It's very harsh and bright.

**Describe the solution you'd like**
Preferrably some way to customize and even disable the tints that get applied in the nether and end. I heavily dislike the end and nether biome tints (excluding the basalt deltas, those look nice) as they're very bright (for example the crimson forest is just all red and the end is just all purple).

There isn't really any additional alternative, just a setting to configure these in any way such as a toggle or even the ability to change the color and intensity would be really nice.

**Additional context**
*The crimson forest is just bright red*
![2021-03-02_19 42 53](https://user-images.githubusercontent.com/18062275/109749487-9f6a0f80-7b8f-11eb-8833-a9e589825494.png)

*The end is just all purple*
![2021-03-02_19 43 18](https://user-images.githubusercontent.com/18062275/109749496-a3962d00-7b8f-11eb-9a31-ad1b47e017ed.png)

**Comment by rre36** [comment]
Settings to adjust the end coloring are not hard to add, gonna include these with the next update.
As for the nether, its a bit more difficult to do that due to nether biomes so i'll likely also provide a setting to adjust the tint saturation to not fully loose the biome coloring as well as an option to override it with a custom color.

**Comment by rre36** [comment]
Done for next update
